Update Bump version (#40)

diff --git a/.github/workflows/release-package.yml b/.github/workflows/release-package.yml
--- a/.github/workflows/release-package.yml
+++ b/.github/workflows/release-package.yml
@@ -11,7 +11,8 @@ jobs:
   publish-package:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Repository
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0  # Ensure full history is fetched for version comparison
 
@@ -27,8 +28,14 @@ jobs:
 
       - name: Bump version in pyproject.toml
         run: |
-          # Bump the version using a patch increment and extract the new version.
-          NEW_VERSION=$(poetry version patch 2>&1 | awk '{print $NF}')
+          git checkout main
+          git pull origin main --rebase
+          
+          NEW_VERSION=$(poetry version patch | awk '{print $NF}')
+          if [[ -z "$NEW_VERSION" ]]; then
+            echo "Error: Failed to extract new version!"
+            exit 1
+          fi
           echo "Bumped version to $NEW_VERSION"
           
           git config user.name "github-release"
@@ -36,7 +43,7 @@ jobs:
           
           git add pyproject.toml
           git commit -m "Bump version to $NEW_VERSION [skip ci]" || echo "No changes to commit."
-          git push
+          git push origin main
 
       - name: Build package
         run: poetry build -f wheel
